<!DOCTYPE html>
<html lang='pl'>
<head>
	<meta charset="utf-8">
	<title>FoodDeli - Jak możemy Ci pomóc?</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  	<link rel="stylesheet" href="main.css">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
	<script src="https://kit.fontawesome.com/6c40eaf681.js" crossorigin="anonymous"></script></head>
<body>

<header></header>

<h2 class='fluid bg-light text-center mb-0 pt-4 pb-3'>Jak możemy Ci pomóc?
</h2>

<div class="row">
	<div class="col-1 bg-light"></div>
	<div class="col-10 bg-light">
		<nav>
  			<div class="nav nav-tabs" id="nav-tab" role="tablist">
    			<a class="nav-item nav-link" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="false">Informacje ogólne</a>
    			<a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Moje konto</a>
    			<a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">Zamówienia</a>
    			<a class="nav-item nav-link" id="nav-payment-tab" data-toggle="tab" href="#nav-payment" role="tab" aria-controls="nav-payment" aria-selected="false">Płatności</a>
    			<a class="nav-item nav-link" id="nav-delivery-tab" data-toggle="tab" href="#nav-delivery" role="tab" aria-controls="nav-delivery" aria-selected="false">Dostawa</a>
  			</div>
		</nav>
		<div class="tab-content" id="nav-tabContent">
  			<div id="nav-home" class="tab-pane fade show bb-0" role="tabpanel" aria-labelledby="nav-home-tab">
  				<div class="row pt-3">
  					<div class="col-4 bg-light">
    					<div class="list-group" id="list-tab" role="tablist">
				      		<a class="list-group-item list-group-item-action active" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home">Jak mogę wystawić opinię?</a>
				      		<a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="#list-profile" role="tab" aria-controls="profile">W jaki sposób uporządkowana jest lista restauracji?</a>
				      		<a class="list-group-item list-group-item-action" id="list-messages-list" data-toggle="list" href="#list-messages" role="tab" aria-controls="messages">Jak ustalana jest kolejność restauracji?</a>
				      		<a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="#list-settings" role="tab" aria-controls="settings">Czy istnieją inne czynniki mające wpływ na wyświetlanie restauracji na liście?</a>
				      		<a class="list-group-item list-group-item-action" id="list-options1-list" data-toggle="list" href="#list-options1" role="tab" aria-controls="settings">Dlaczego pod nazwą niektórych restauracji znajduje się napis „Sponsorowane”?</a>
				      		<a class="list-group-item list-group-item-action" id="list-options2-list" data-toggle="list" href="#list-options2" role="tab" aria-controls="settings">Jak mogę udostępnić opinię?</a>
				      		<a class="list-group-item list-group-item-action" id="list-options3-list" data-toggle="list" href="#list-options3" role="tab" aria-controls="settings">Co robi FoodDeli.pl, aby zapobiec rozprzestrzenianiu się COVID-19?</a>
    					</div>
  					</div>
 					<div class="col-8 border pt-3 pb-3">
    					<div class="tab-content" id="nav-tabContent">
      						<div class="tab-pane fade show active" id="list-home" role="tabpanel" aria-labelledby="list-home-list" style="text-indent: 5%;">
      							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam.
      						</div>
      						<div class="tab-pane fade" id="list-profile" role="tabpanel" aria-labelledby="list-profile-list" style="text-indent: 5%;">
      							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam.
      						</div>
      						<div class="tab-pane fade" id="list-messages" role="tabpanel" aria-labelledby="list-messages-list" style="text-indent: 5%;">
      							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam.
      						</div>
     	 					<div class="tab-pane fade" id="list-settings" role="tabpanel" aria-labelledby="list-settings-list" style="text-indent: 5%;">
     	 						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam
							</div>
							<div class="tab-pane fade" id="list-options1" role="tabpanel" aria-labelledby="list-options1-list" style="text-indent: 5%;">
     	 						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam
							</div>
							<div class="tab-pane fade" id="list-options2" role="tabpanel" aria-labelledby="list-options2-list" style="text-indent: 5%;">
     	 						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam
							</div>
							<div class="tab-pane fade" id="list-options3" role="tabpanel" aria-labelledby="list-options3-list" style="text-indent: 5%;">
     	 						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam
							</div>
    					</div>
  					</div>
				</div>
  			</div>
  			<div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
  				<div class="row pt-3">
  					<div class="col-4 bg-light">
    					<div class="list-group" id="list-tab" role="tablist">
				      		<a class="list-group-item list-group-item-action active" id="list-home-list1" data-toggle="list" href="#list-home1" role="tab" aria-controls="home1">Jak zaktualizować dane konta?</a>
				      		<a class="list-group-item list-group-item-action" id="list-profile-list1" data-toggle="list" href="#list-profile1" role="tab" aria-controls="profile1">Jak założyć konto?</a>
				      		<a class="list-group-item list-group-item-action" id="list-messages-list1" data-toggle="list" href="#list-messages1" role="tab" aria-controls="messages1">Dlaczego warto założyć konto?</a>
				      		<a class="list-group-item list-group-item-action" id="list-settings-list1" data-toggle="list" href="#list-settings1" role="tab" aria-controls="settings1">Nie pamiętam hasła. Co mam zrobić?</a>
				      		<a class="list-group-item list-group-item-action" id="list-options1-list1" data-toggle="list" href="#list-options11" role="tab" aria-controls="settings1">Jak usunąć konto?</a>
				      		<a class="list-group-item list-group-item-action" id="list-options2-list1" data-toggle="list" href="#list-options21" role="tab" aria-controls="settings1">Jaka jest polityka prywatności FoodDeli.pl?</a>
				      		<a class="list-group-item list-group-item-action" id="list-options3-list1" data-toggle="list" href="#list-options31" role="tab" aria-controls="settings1">Gdzie znajdę regulamin FoodDeli.pl?</a>
    					</div>
  					</div>
 					<div class="col-8 border pt-3 pb-3">
    					<div class="tab-content" id="nav-tabContent">
      						<div class="tab-pane fade show active" id="list-home1" role="tabpanel" aria-labelledby="list-home-list1" style="text-indent: 5%;">
      							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam.
      						</div>
      						<div class="tab-pane fade" id="list-profile1" role="tabpanel" aria-labelledby="list-profile-list1" style="text-indent: 5%;">
      							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam.
      						</div>
      						<div class="tab-pane fade" id="list-messages1" role="tabpanel" aria-labelledby="list-messages-list1" style="text-indent: 5%;">
      							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam.
      						</div>
     	 					<div class="tab-pane fade" id="list-settings1" role="tabpanel" aria-labelledby="list-settings-list1" style="text-indent: 5%;">
     	 						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam
							</div>
							<div class="tab-pane fade" id="list-options11" role="tabpanel" aria-labelledby="list-options1-list1" style="text-indent: 5%;">
     	 						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam
							</div>
							<div class="tab-pane fade" id="list-options21" role="tabpanel" aria-labelledby="list-options2-list1" style="text-indent: 5%;">
     	 						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam
							</div>
							<div class="tab-pane fade" id="list-options31" role="tabpanel" aria-labelledby="list-options3-list1" style="text-indent: 5%;">
     	 						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam
							</div>
    					</div>
  					</div>
				</div>
  			</div>
  			<div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
  				<div class="row pt-3">
  					<div class="col-4 bg-light">
    					<div class="list-group" id="list-tab" role="tablist">
				      		<a class="list-group-item list-group-item-action active" id="list-home-list11" data-toggle="list" href="#list-home11" role="tab" aria-controls="home1">Składanie zamówienia</a>
				      		<a class="list-group-item list-group-item-action" id="list-profile-list11" data-toggle="list" href="#list-profile11" role="tab" aria-controls="profile1">Informacje o moim zamówieniu</a>
				      		<a class="list-group-item list-group-item-action" id="list-messages-list11" data-toggle="list" href="#list-messages11" role="tab" aria-controls="messages1">Problemy z moim zamówieniem</a>
				      		<a class="list-group-item list-group-item-action" id="list-settings-list11" data-toggle="list" href="#list-settings11" role="tab" aria-controls="settings1">Anulowanie zamówienia</a>
				      		<a class="list-group-item list-group-item-action" id="list-options1-list11" data-toggle="list" href="#list-options111" role="tab" aria-controls="settings1">Jakość jedzenia</a>
    					</div>
  					</div>
 					<div class="col-8 border pt-3 pb-3">
    					<div class="tab-content" id="nav-tabContent">
      						<div class="tab-pane fade show active" id="list-home11" role="tabpanel" aria-labelledby="list-home-list11" style="text-indent: 5%;">
      							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam.
      						</div>
      						<div class="tab-pane fade" id="list-profile11" role="tabpanel" aria-labelledby="list-profile-list11" style="text-indent: 5%;">
      							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam.
      						</div>
      						<div class="tab-pane fade" id="list-messages11" role="tabpanel" aria-labelledby="list-messages-list11" style="text-indent: 5%;">
      							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam.
      						</div>
     	 					<div class="tab-pane fade" id="list-settings11" role="tabpanel" aria-labelledby="list-settings-list11" style="text-indent: 5%;">
     	 						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam
							</div>
							<div class="tab-pane fade" id="list-options111" role="tabpanel" aria-labelledby="list-options1-list11" style="text-indent: 5%;">
     	 						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam
							</div>
    					</div>
  					</div>
				</div>
  			</div>
  			<div class="tab-pane fade" id="nav-payment" role="tabpanel" aria-labelledby="nav-payment-tab">
  				<div class="row pt-3">
  					<div class="col-4 bg-light">
    					<div class="list-group" id="list-tab" role="tablist">
				      		<a class="list-group-item list-group-item-action active" id="list-home-list4" data-toggle="list" href="#list-home4" role="tab" aria-controls="home1">Z jakich metod płatności mogę skorzystać?</a>
				      		<a class="list-group-item list-group-item-action" id="list-profile-list4" data-toggle="list" href="#list-profile4" role="tab" aria-controls="profile1">Czy moje płatności online są bezpieczne?</a>
				      		<a class="list-group-item list-group-item-action" id="list-messages-list4" data-toggle="list" href="#list-messages4" role="tab" aria-controls="messages1">Moja płatność online nie powiodła się. Co mam zrobić?</a>
				      		<a class="list-group-item list-group-item-action" id="list-settings-list4" data-toggle="list" href="#list-settings4" role="tab" aria-controls="settings1">Czy naliczane są dodatkowe opłaty w przypadku płatności online?</a>
				      		<a class="list-group-item list-group-item-action" id="list-options1-list4" data-toggle="list" href="#list-options4" role="tab" aria-controls="settings1">Jak otrzymać fakturę za zamówienie?</a>
				      		<a class="list-group-item list-group-item-action" id="list-options2-list4" data-toggle="list" href="#list-options4" role="tab" aria-controls="settings1">Chcę uzyskać zwrot pieniędzy.</a>
				      		<a class="list-group-item list-group-item-action" id="list-options3-list4" data-toggle="list" href="#list-options4" role="tab" aria-controls="settings1">Kody rabatowe</a>
    					</div>
  					</div>
 					<div class="col-8 border pt-3 pb-3">
    					<div class="tab-content" id="nav-tabContent">
      						<div class="tab-pane fade show active" id="list-home4" role="tabpanel" aria-labelledby="list-home-list4" style="text-indent: 5%;">
      							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam.
      						</div>
      						<div class="tab-pane fade" id="list-profile4" role="tabpanel" aria-labelledby="list-profile-list4" style="text-indent: 5%;">
      							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam.
      						</div>
      						<div class="tab-pane fade" id="list-messages4" role="tabpanel" aria-labelledby="list-messages-list4" style="text-indent: 5%;">
      							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam.
      						</div>
     	 					<div class="tab-pane fade" id="list-settings4" role="tabpanel" aria-labelledby="list-settings-list4" style="text-indent: 5%;">
     	 						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam
							</div>
							<div class="tab-pane fade" id="list-options4" role="tabpanel" aria-labelledby="list-options1-list4" style="text-indent: 5%;">
     	 						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam
							</div>
							<div class="tab-pane fade" id="list-options4" role="tabpanel" aria-labelledby="list-options2-list4" style="text-indent: 5%;">
     	 						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam
							</div>
							<div class="tab-pane fade" id="list-options4" role="tabpanel" aria-labelledby="list-options3-list4" style="text-indent: 5%;">
     	 						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam
							</div>
    					</div>
  					</div>
				</div>
  			</div>
  			<div class="tab-pane fade" id="nav-delivery" role="tabpanel" aria-labelledby="nav-delivery-tab">
  				<div class="row pt-3">
  					<div class="col-4 bg-light">
    					<div class="list-group" id="list-tab" role="tablist">
				      		<a class="list-group-item list-group-item-action active" id="list-home-list5" data-toggle="list" href="#list-home5" role="tab" aria-controls="home1">Co to jest Food Tracker?</a>
				      		<a class="list-group-item list-group-item-action" id="list-profile-list5" data-toggle="list" href="#list-profile5" role="tab" aria-controls="profile1">Jak sprawdzić, czy zamówienie zostało potwierdzone?</a>
				      		<a class="list-group-item list-group-item-action" id="list-messages-list5" data-toggle="list" href="#list-messages5" role="tab" aria-controls="messages1">Jak obliczany jest czas dostawy?</a>
				      		<a class="list-group-item list-group-item-action" id="list-settings-list5" data-toggle="list" href="#list-settings5" role="tab" aria-controls="settings1">Mam zastrzeżenia do kuriera.</a>
    					</div>
  					</div>
 					<div class="col-8 border pt-3 pb-3">
    					<div class="tab-content" id="nav-tabContent">
      						<div class="tab-pane fade show active" id="list-home5" role="tabpanel" aria-labelledby="list-home-list5" style="text-indent: 5%;">
      							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam.
      						</div>
      						<div class="tab-pane fade" id="list-profile5" role="tabpanel" aria-labelledby="list-profile-list5" style="text-indent: 5%;">
      							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam.
      						</div>
      						<div class="tab-pane fade" id="list-messages5" role="tabpanel" aria-labelledby="list-messages-list5" style="text-indent: 5%;">
      							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam.
      						</div>
     	 					<div class="tab-pane fade" id="list-settings5" role="tabpanel" aria-labelledby="list-settings-list5" style="text-indent: 5%;">
     	 						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra eget sem nec euismod. Nam egestas vehicula arcu eget pulvinar. Nunc vitae egestas lorem. Phasellus vel auctor justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis convallis venenatis. Sed ac massa massa. Ut a magna velit. Mauris at lacus diam. In varius sapien arcu, in commodo justo condimentum eget. Morbi hendrerit quam sed turpis elementum, id malesuada est molestie. Fusce ullamcorper ultricies lectus, vitae pellentesque mi. Maecenas facilisis turpis vel odio finibus feugiat. Maecenas lacinia, lacus placerat laoreet vehicula, risus lectus efficitur turpis, vel pulvinar felis diam a tortor. In hac habitasse platea dictumst. Nam tincidunt augue arcu, et lobortis turpis eleifend at.

								Phasellus sit amet nisl non diam bibendum bibendum et vel augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet tempor dapibus. Morbi vel mi ac arcu fermentum convallis sed eu dolor. Fusce hendrerit enim eu nisi pulvinar, sed ultrices mi molestie. Aenean pellentesque, mi sit amet ornare fermentum, augue sem placerat mi, vitae cursus nibh tortor ac dolor. Pellentesque facilisis dignissim lorem, id porttitor tortor sollicitudin vitae. Donec ac nisi et dolor iaculis varius. Fusce nibh velit, dictum sed augue viverra, tincidunt suscipit magna. Ut eu fringilla lorem, eget feugiat mi. Suspendisse vel suscipit dolor, non rutrum tortor. Morbi molestie dolor convallis urna elementum, quis volutpat leo rhoncus. Vivamus tempor diam quis diam porta iaculis. In vel luctus odio.

								Sed finibus libero at feugiat ultrices. Nullam sagittis porta sem. Sed volutpat nisl turpis, nec consequat diam dignissim ac. Praesent condimentum purus eu bibendum cursus. Ut iaculis tempor neque a ultrices. Donec mollis sapien in mauris lacinia, in suscipit ante gravida. Sed sed condimentum diam.
							</div>
    					</div>
  					</div>
				</div>
  			</div>
		</div>
	</div>
	<div class="col-1 bg-light"></div>
</div>

<footer class="page-footer font-small bg-light">
	<div class="footer-copyright text-center py-3">© 2022 Copyright:
    	<a href="https://moodle.uwm.edu.pl/enrol/index.php?id=5426/" style="color:black"> FoodDeli.pl</a>
  	</div>
</footer>

<script>
	$("header").load("navbar.php");
	var hash = $(location).attr('hash');
	if(hash !== "")
		$('[href="'+hash+'"]').tab('show');
	else
		$('[href="#nav-home"]').tab('show');
</script>

</body>
</html>